### ISSUE TITLE
remove redundant License info (or move to the bottom)

### ISSUE THREAD

**Issue by cpauvert** [NFDI4Microbiota/MetadataStandards#19]

**Comment by pojith** [comment]
i can take this issues

**Comment by cpauvert** [comment]
> i can take this issues

Awesome, thanks! Do not hesitate to assign me for a review of your PR if you'd like : )

**Comment by pojith** [comment]
can provide  example details like about redundant lincense

**Comment by cpauvert** [comment]
> can provide example details like about redundant lincense

Hi, I'm afraid I do not understand what you mean with this comment. Do you want more information on what to edit?

**Comment by pojith** [comment]
i want  information on what to edit

**Comment by cpauvert** [comment]
> i want information on what to edit

The idea was to move the section relating to the license of the repository to the bottom of the README file. This was done in commit e33218b, sorry, therefore I'm closing this issue.

Thanks a lot for stepping in @pojith, future contributions are of course welcome. We have added now a[ Code of Conduct ](https://github.com/NFDI4Microbiota/MetadataStandards/blob/main/CODE_OF_CONDUCT.md)to explain how we expect interactions between collaborators. Feel free to have a look!

Best,
