### ISSUE TITLE
Closing the general issues?

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/MetadataStandards#27]
Hey, 

in the beginning Nathan opened a few general issues referig to the different techniques in hopes of getting explicit feedback.
After 2 years without comments/ questions, can we close these and hope that people will create new issues with enough context?
Specifically: 
- #7 
- #6 
- #5 
- #4 
- #3 
- #2 
- #1 

Thanks for having a look and making a decision, @MartinBoleSlo !

**Comment by MartinBoleSlo** [comment]
Hey Maja,

I closed all the issues except the #1, which I will be keeping open until we come to a decision there.

**Comment by magelm** [comment]
Thanks Martin and sounds good! I'll close this issue as this was intended for cleaning up the issues and not having more open :D
