### ISSUE TITLE
Adding depth field to other biomes?

### ISSUE THREAD

**Issue by magelm** [NFDI4Microbiota/MetadataStandards#30]
Hey, 
I noticed that `depth` is part of [animal-associated metadata](https://github.com/NFDI4Microbiota/MetadataStandards/blob/2b050dc62d261a0ed5cfa7cc9e4746a995c726c2/Biological_Environmental/AnimalAssoc_BioEnv_Metadata.md?plain=1#L14) and [marine](https://github.com/NFDI4Microbiota/MetadataStandards/blob/2b050dc62d261a0ed5cfa7cc9e4746a995c726c2/Biological_Environmental/Marine_BioEnv_Metadata.md?plain=1#L14) but not [terrestrial](https://github.com/NFDI4Microbiota/MetadataStandards/blob/2b050dc62d261a0ed5cfa7cc9e4746a995c726c2/Biological_Environmental/Terrestrial_BioEnv_Metadata.md) even though the description mentions soil. 

Should this term be added to all biomes, as plant-associated root samples could make use of the `depth` term as well?
Could be used for human-associated as well, if somebody digs out a body, or not?

**Comment by MartinBoleSlo** [comment]
Added fields to suggested tables. Make sense, if nothing else, the ancient samples had to come from somewhere.
